### ISSUE TITLE
Support proper TLS cert/verification on hidviz.org

### ISSUE THREAD

**Issue by craftyguy** [ondrejbudai/hidviz#12]
I'm maintaining the Arch Linux package (just in case you don't remember me) and currently hidviz.org's HTTPS TLS cert fails server verification (the cert's domain doesn't match the url). This is very important for insuring some amount of integrity for the source code.

**Comment by ondrejbudai** [comment]
Sorry for the delay. I will be looking into this today, please expect possible outage on hidviz.org.

**Comment by ondrejbudai** [comment]
Aaaaand done. Currently using Cloudflare as proxy. It isn't perfect, but it works.

**Comment by craftyguy** [comment]
Just curious, why not use Let's Encrypt for a free TLS cert instead? It's certainly more trustworthy than proxying through cloudflare.. where the traffic could easily be MITMed by them.

**Comment by ondrejbudai** [comment]
It's currently the easiest way. The webpage is hosted on github pages which doesn't support custom SSL certificates. Therefore using proxy is the only option. I'm currently looking into migrating the project somewhere else. My requirements are low price or better free and SSL support. If you have any ideas I will be glad. :)

**Comment by ondrejbudai** [comment]
FYI hidviz.org now works with our own Let's encrypt certificate on GH pages.
