### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by yackermann** [ondrejbudai/hidviz#13]
Any advice on compiling for OSX?

**Comment by ondrejbudai** [comment]
I will look into compiling for OSX later in september as I don't have access to any apple computer at this time.

**Comment by BoLaMN** [comment]
it compiles fine, https://cldup.com/cngJzqVwWO.png thou selecting anything gets an error of `Claiming the interface failed: -3: Unknown error -3`

**Comment by ondrejbudai** [comment]
We now have experimental MacOS support, closing. Feel free to report any bugs. :)
