### ISSUE TITLE
Build error on Arch Linux with version 0.1.4

### ISSUE THREAD

**Issue by Styx85** [ondrejbudai/hidviz#20]
Unfortunately it does not build on Arch with the provided AUR Package. And sorry for the long quote.

> [caberliner@home ~]$ pacaur -S hidviz
> :: Package hidviz not found in repositories, trying AUR...
> :: resolving dependencies...
> :: looking for inter-conflicts...
> 
> AUR Packages  (1) hidviz-0.1.4-1  
> 
> :: Proceed with installation? [Y/n] 
> 
> :: Retrieving package(s)...
> :: hidviz build files are up-to-date -- skipping
> :: Checking hidviz integrity...
> ==> Making package: hidviz 0.1.4-1 (So 31. Dez 16:43:32 CET 2017)
> ==> Retrieving sources...
>   -> Found hidviz-0.1.4.tar.gz
> ==> Validating source files with sha256sums...
>     hidviz-0.1.4.tar.gz ... Passed
> :: Building hidviz package(s)...
> ==> Making package: hidviz 0.1.4-1 (So 31. Dez 16:43:41 CET 2017)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> WARNING: Using existing $srcdir/ tree
> ==> Removing existing $pkgdir/ directory...
> ==> Starting build()...
> [  2%] Running C++ protocol buffer compiler on src/Buffer.proto
> Scanning dependencies of target hidx_server
> [  5%] Building CXX object libhidx/libhidx_server/CMakeFiles/hidx_server.dir/Buffer.pb.cc.o
> [  8%] Building CXX object libhidx/libhidx_server/CMakeFiles/hidx_server.dir/src/Server.cc.o
> [ 11%] Building CXX object libhidx/libhidx_server/CMakeFiles/hidx_server.dir/src/Utils.cc.o
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc: In function 'void libhidx::server::run(std::__cxx11::string, bool)':
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:387:14: error: 'function' is not a member of 'std'
>          std::function<void(const asio::error_code& ec)> timerHandler;
>               ^~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:387:14: note: suggested alternative: 'is_function'
>          std::function<void(const asio::error_code& ec)> timerHandler;
>               ^~~~~~~~
>               is_function
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:387:23: error: expected primary-expression before 'void'
>          std::function<void(const asio::error_code& ec)> timerHandler;
>                        ^~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:389:9: error: 'timerHandler' was not declared in this scope
>          timerHandler = [&](const asio::error_code&) {
>          ^~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:389:9: note: suggested alternative: 'file_handle'
>          timerHandler = [&](const asio::error_code&) {
>          ^~~~~~~~~~~~
>          file_handle
> In file included from /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio.hpp:42:0,
>                  from /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/include/libhidx/server/Utils.hh:27,
>                  from /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:24:
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc: In member function 'void libhidx::server::Loop::operator()(asio::error_code, std::size_t)':
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:304:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
>            case -1: if (_coro_value) \
>                     ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>  define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:338:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(8), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:13: note: here
>              case 1: if (_coro_value) \
>              ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:338:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(8), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
>              case 1: if (_coro_value) \
>                      ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:338:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(8), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:309:18: note: here
>              else case 0:
>                   ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:338:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(8), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:304:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
>            case -1: if (_coro_value) \
>                     ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:346:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(m_dataLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:13: note: here
>              case 1: if (_coro_value) \
>              ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>  define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:346:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(m_dataLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
>              case 1: if (_coro_value) \
>                      ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:346:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(m_dataLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:309:18: note: here
>              else case 0:
>                   ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:346:21: note: in expansion of macro 'yield'
>                      yield asio::async_read(m_socket, m_buffer->prepare(m_dataLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:304:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
>            case -1: if (_coro_value) \
>                     ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:358:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(messageLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:13: note: here
>              case 1: if (_coro_value) \
>              ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:358:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(messageLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
>              case 1: if (_coro_value) \
>                      ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:358:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(messageLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:309:18: note: here
>              else case 0:
>                   ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:358:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(messageLength), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:304:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
>            case -1: if (_coro_value) \
>                     ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:359:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(m_messageOut), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:13: note: here
>              case 1: if (_coro_value) \
>              ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:359:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(m_messageOut), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:307:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
>              case 1: if (_coro_value) \
>                      ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:359:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(m_messageOut), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:309:18: note: here
>              else case 0:
>                   ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:324:26: note: in expansion of macro 'ASIO_CORO_YIELD_IMPL'
>   define ASIO_CORO_YIELD ASIO_CORO_YIELD_IMPL(__LINE__)
>                           ^~~~~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:18:16: note: in expansion of macro 'ASIO_CORO_YIELD'
>   define yield ASIO_CORO_YIELD
>                 ^~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:359:21: note: in expansion of macro 'yield'
>                      yield asio::async_write(m_socket, asio::buffer(m_messageOut), *this);
>                      ^~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:283:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
>      case -1: if (_coro_value) \
>               ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:14:21: note: in expansion of macro 'ASIO_CORO_REENTER'
>   define reenter(c) ASIO_CORO_REENTER(c)
>                      ^~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:336:13: note: in expansion of macro 'reenter'
>              reenter(this) {
>              ^~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/coroutine.hpp:292:10: note: here
>      else case 0:
>           ^
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/build/libhidx/asio/asio/include/asio/yield.hpp:14:21: note: in expansion of macro 'ASIO_CORO_REENTER'
>   define reenter(c) ASIO_CORO_REENTER(c)
>                      ^~~~~~~~~~~~~~~~~
> /home/caberliner/.cache/pacaur/hidviz/src/hidviz-0.1.4/libhidx/libhidx_server/src/Server.cc:336:13: note: in expansion of macro 'reenter'
>              reenter(this) {
>              ^~~~~~~
> make[2]: *** [libhidx/libhidx_server/CMakeFiles/hidx_server.dir/build.make:71: libhidx/libhidx_server/CMakeFiles/hidx_server.dir/src/Server.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:255: libhidx/libhidx_server/CMakeFiles/hidx_server.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
> :: failed to build hidviz package(s)
>

**Comment by craftyguy** [comment]
Looks like this commit in libhidx is not being pulled in when the submodule is cloned since the AUR package is using the release tagged @ 0.1.4: https://github.com/ondrejbudai/libhidx/commit/25588b010db1d9b8cb1b29c9552648355a7f2f53

@ondrejbudai Could you tag a new release off of master so that I can update my package in Arch Linux's AUR to build it instead of the current latest release (0.1.4) ?

**Comment by albfan** [comment]
There's a fix on libhidx and another on this repo master .So a release make totally sense.

Or we can add a hidviz-git package to relay on master.

I tried the fix and program works as expected, so I strongly suggest to do a new release

**Comment by ondrejbudai** [comment]
0.1.5 released :fireworks: 

https://hidviz.org/releases/hidviz-0.1.5.tar.gz
