### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by lgbaldoni** [ondrejbudai/hidviz#27]
Using gcc9/binutils 2.3.4 and Qt 5.14.1 on openSUSE Tumbleweed.

See log [snippet](https://github.com/ondrejbudai/hidviz/files/4454477/hidviz_linking.txt).

P.S: I've also tried clang/gold, but it makes no difference.

**Comment by ondrejbudai** [comment]
The issue is caused by cmake 3.17, I was able to reproduce on Fedora. My first attempt to fix it wasn't successful, I will continue later this weekend.

**Comment by lgbaldoni** [comment]
The problem can apparently go away with meson, see my fork [here](https://github.com/lgbaldoni/hidviz/tree/meson).

That would solve the moc header trouble, at least for linux.

**Comment by lgbaldoni** [comment]
How silly of me, adding `cmake_policy(SET CMP0100 NEW)` was all I needed.
I suppose you are looking for a more nuanced approach because of old cmake versions on some targets?

**Comment by ondrejbudai** [comment]
Exactly, the weird thing is that this worked before 3.17 just fine, I don't understand why they introduced the policy.

**Comment by lgbaldoni** [comment]
How about something like:
```
if (CMAKE_VERSION VERSION_GREATER_EQUAL 3.17)
  cmake_policy(SET CMP0100 NEW)
endif()
```
?

**Comment by yarda** [comment]
@ondrejbudai any progress with this? It's blocking hidviz rebuild for f33. I guess it will be soon problem on other distros as well. I used patch proposed by @lgbaldoni in f33 and it seems it works OK.
