### ISSUE TITLE
Mac updates

### ISSUE THREAD

**Issue by m5p3nc3r** [ondrejbudai/hidviz#32]
Hi community

I have hidviz working on my mac, it only needs a few brew packages installed (cmake, qt@5, libusb protobuf) and an update to the CMakeLists.txt as below

```
diff --git a/hidviz/CMakeLists.txt b/hidviz/CMakeLists.txt
index f46f61e..3dde377 100644
--- a/hidviz/CMakeLists.txt
+++ b/hidviz/CMakeLists.txt
@@ -13,6 +13,9 @@ endif()
 # Find the QtWidgets library
 find_package(Qt5 REQUIRED COMPONENTS Widgets)
 
+find_package(Protobuf REQUIRED)
+include_directories(${PROTOBUF_INCLUDE_DIRS})
+
 set(CMAKE_AUTOMOC ON)
 set(CMAKE_AUTOUIC ON)
 set(CMAKE_AUTORCC ON)
```

Would you like me to create a PR containing this and updating the documentation accordingly?

**Comment by ondrejbudai** [comment]
Sure, that would be lovely, thanks!

**Comment by m5p3nc3r** [comment]
Sorry - I have been dragging my heels on this - I promise I will get something here soon.

I have however been playing with the idea of using [WEBHid](https://wicg.github.io/webhid/) so that you can potentially have the same functionality in a browser with no need to install an application.  Only works on the latests Chrome, Edge and Opera browsers (as they support the navigator.hid interface).  The presentation is awful at the moment, but its mostly functional.

You can see a live version at: https://m5p3nc3r.github.io/webhidviz/
with the sources available at: https://github.com/m5p3nc3r/webhidviz

This a snapshot of it decoding a PS4 controller
<img width="705" alt="Screenshot 2022-04-29 at 17 47 27" src="https://user-images.githubusercontent.com/1710852/165988370-020698b8-807e-4550-b0d8-d37c4d371027.png">

**Comment by ondrejbudai** [comment]
Very nice project, thanks for sharing!

**Comment by m5p3nc3r** [comment]
I have create #33 that adds the instructions and changes needed to build for Mac.

Hope this works for you.
