### ISSUE TITLE
qt6 is a mighty bore

### ISSUE THREAD

**Issue by rmsa5** [ondrejbudai/hidviz#38]
It would seem the most common linux distro (ubuntu, linuxmint) doesn't provide qt6 packages. Have users managed to work around this issue? thanks in advance for the help.

**Comment by ondrejbudai** [comment]
Ubuntu 22.04 ships with QT6, see https://packages.ubuntu.com/search?keywords=qt6&searchon=names&suite=jammy&section=all

Linux Mint 54 is based on 22.04, so I presume the same thing applies there as well.

If your distribution doesn't ship Qt6, you can still hidviz 0.1.5, there are no new features in 0.2, so it should work just fine. :)

**Comment by ondrejbudai** [comment]
FTR, this is now verified in the CI: https://github.com/hidviz/hidviz/pull/39 :)
